steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_ENV=production'
      - '--build-arg'
      - 'VITE_APP_HOST=https://us-creators.cmoney.tw'
      - '--build-arg'
      - 'VITE_CLIENT_ID=cm-tian-compounding-web'
      - '--build-arg'
      - 'VITE_AUTH_HOST=https://auth.cmoney.tw'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tian-academy-production:latest'
      - '.'
images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tian-academy-production:latest'
